<div class="content clearfloat">
    <div class="content-left">
        <div class="pin">
            <div class="pin-head pin-head-1">
                <p>我们的价值观</p>
                <ul>
                <li class="active"><a href="/index/module/mid/1">理解阅读</a>
                        <div class="angle"></div>
                    </li>
                    <li><a href="/index/module/mid/2">践行动态</a>
                        <div class="angle"></div>
                    </li>
                    <li><a href="/index/module/mid/3">榜样领行</a>
                        <div class="angle"></div>
                    </li>
                </ul>
            </div>
            <div class="fuck1 active">
                <div id="fsD1" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic1" class="fPic">
                        <?php
                         if ($this->modules[0]) {
                           for ($i=0; $i < count($this->modules[0]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[0]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt1">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[0]) {
                       for ($i=0; $i < count($this->modules[0]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[0]['article'][$i]['id']."\">".$this->modules[0]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
            <div class="fuck1">
                <div id="fsD2" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic2" class="fPic">
                        <?php
                         if ($this->modules[2]) {
                           for ($i=0; $i < count($this->modules[2]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[2]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt2">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[1]) {
                       for ($i=0; $i < count($this->modules[1]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[1]['article'][$i]['id']."\">".$this->modules[1]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
            <div class="fuck1">
                <div id="fsD3" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic3" class="fPic">
                        <?php
                         if ($this->modules[2]) {
                           for ($i=0; $i < count($this->modules[2]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[2]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt3">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[2]) {
                       for ($i=0; $i < count($this->modules[2]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[2]['article'][$i]['id']."\">".$this->modules[2]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
        </div>
        <div class="fuck">
            <div class="fuck-left">
                <img src="/images/index/zhuanti.jpg" alt=""/>
            </div>
            <a href="http://news.hfut.edu.cn/list-111-1.html" target="_blank" class="fuck-right">
                <img src="/images/index/1.jpg" alt=""/>
                <span class="opacity">
                    <p>群众路线</p>
                </span>
            </a>
            <a href="http://uzone.univs.cn/special/1/1304/index.html" target="_blank" class="fuck-right">
                <img src="/images/index/2.jpg" alt=""/>
                <span class="opacity">
                    <p>道德实践</p>
                </span>
            </a>
            <a href="http://news.hfut.edu.cn/index.php?m=content&c=index&a=lists&catid=126" target="_blank" class="fuck-right">
                <img src="/images/index/3.jpg" alt=""/>
                <span class="opacity">
                    <p>社会主义核心价值观</p>
                </span>
            </a>
            <a href="http://news.hfut.edu.cn/list-98-1.html" target="_blank" class="fuck-right">
                <img src="/images/index/4.jpg" alt=""/>
                <span class="opacity">
                    <p>我的中国梦</p>
                </span>
            </a>
            <a href="http://uzone.univs.cn/special/1/802/index.html" target="_blank" class="fuck-right">
                <img src="/images/index/5.jpg" alt=""/>
                <span class="opacity">
                    <p>五四劳动节</p>
                </span>
            </a>
            <a href="http://votesys.hfutonline.net/index/vote" target="_blank" class="fuck-right">
                <img src="/images/index/6.jpg" alt=""/>
                <span class="opacity">
                    <p>十佳大学生</p>
                </span>
            </a>
            <a href="http://news.hfut.edu.cn/index.php?m=content&c=index&a=lists&catid=53" target="_blank" class="fuck-right">
                <img src="/images/index/7.jpg" alt=""/>
                <span class="opacity">
                    <p>学风在线</p>
                </span>
            </a>
            <a href="http://news.hfut.edu.cn/index.php?m=content&c=index&a=lists&catid=66" target="_blank" class="fuck-right">
                <img src="/images/index/8.jpg" alt=""/>
                <span class="opacity">
                    <p>读书专题</p>
                </span>
            </a>
        </div>
        <div class="pin">
            <div class="pin-head pin-head-2">
                <p>众创空间</p>
                <ul>
                    <li class="active"><a href="/index/module/mid/4">创新校园</a>
                        <div class="angle"></div>
                    </li>
                    <li><a href="/index/module/mid/5">科技视点</a>
                        <div class="angle"></div>
                    </li>
                    <li><a href="/index/module/mid/6">作品展示</a>
                        <div class="angle"></div>
                    </li>
                </ul>
            </div>
            <div class="fuck2 active">
                <div id="fsD4" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic4" class="fPic">
                        <?php
                         if ($this->modules[3]) {
                           for ($i=0; $i < count($this->modules[3]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[3]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt4">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[3]) {
                       for ($i=0; $i < count($this->modules[3]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[3]['article'][$i]['id']."\">".$this->modules[3]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
            <div class="fuck2">
                <div id="fsD5" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic5" class="fPic">
                        <?php
                         if ($this->modules[4]) {
                           for ($i=0; $i < count($this->modules[4]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[4]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt5">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[4]) {
                       for ($i=0; $i < count($this->modules[4]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[4]['article'][$i]['id']."\">".$this->modules[4]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
            <div class="fuck2">
                <div id="fsD6" class="focus hehe1" style="width: 310px;height: 260px;">
                    <div id="D1pic6" class="fPic">
                        <?php
                         if ($this->modules[5]) {
                           for ($i=0; $i < count($this->modules[5]['album']); $i++) {
                            echo "<div class=\"fcon\" style=\"display: none;\"><img src=\"".$this->modules[5]['album'][$i]['path']."\" style=\"opacity:1;width: 310px;height: 260px;\"></div>";
                           }
                         }
                        ?>
                    </div>
                    <div class="fbg">
                        <div class="D1fBt" id="D1fBt6">
                            <a href="javascript:void(0)" hidefocus="true"><i>1</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>2</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>3</i></a>
                            <a href="javascript:void(0)" hidefocus="true"><i>4</i></a>
                        </div>
                    </div>
                </div>
                <ul class="pin-right">
                    <?php
                     if ($this->modules[5]) {
                       for ($i=0; $i < count($this->modules[5]['article']); $i++) {
                        echo "<li><a href=\"/index/article/aid/".$this->modules[5]['article'][$i]['id']."\">".$this->modules[5]['article'][$i]['title']."</a></li>";
                       }
                     }
                    ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="content-right">
        <form action="/index/search">
        <input class="search" name="kw" type="text" placeholder="搜索"/>
        <input class="search-btn" type="submit" value="搜索"/>
        </form>
        <div class="ping">
        <p class="ping-title"><a href="/index/module/mid/7" style="color: #555;">hfuter观点</a></p>
            <ul class="ping-link">
                <?php
                 if ($this->modules[6]) {
                   for ($i=0; $i < count($this->modules[6]['article']); $i++) {
                    echo "<li><a href=\"/index/article/aid/".$this->modules[6]['article'][$i]['id']."\">".$this->modules[6]['article'][$i]['title']."</a></li>";
                   }
                 }
                ?>
            </ul>
        </div>
        <div class="ping">
        <p class="ping-title"><a href="/index/module/mid/8" style="color: #555;">经典导读</a></p>
            <ul class="ping-link">
                <?php
                 if ($this->modules[7]) {
                   for ($i=0; $i < count($this->modules[7]['article']); $i++) {
                    echo "<li><a href=\"/index/article/aid/".$this->modules[7]['article'][$i]['id']."\">".$this->modules[7]['article'][$i]['title']."</a></li>";
                   }
                 }
                ?>
            </ul>
        </div>
        <div class="ping">
            <p class="ping-title"><a href="/index/module/mid/9" style="color: #555;">廉洁修身</a></p>
            <ul class="ping-link">
                <?php
                 if ($this->modules[8]) {
                   for ($i=0; $i < count($this->modules[8]['article']); $i++) {
                    echo "<li><a href=\"/index/article/aid/".$this->modules[8]['article'][$i]['id']."\">".$this->modules[8]['article'][$i]['title']."</a></li>";
                   }
                 }
                ?>
            </ul>
        </div>
    </div>
</div>

<div class="fucked">
    <div class="pin-head">
        <p>弘德先锋</p>
        <ul>
            <li class="active"><a href="/index/module/mid/10">个人风采</a>
                <div class="angle"></div>
            </li>
            <li><a href="/index/module/mid/11">集体巡礼</a>
                <div class="angle"></div>
            </li>
        </ul>
    </div>
    <ul class="fucked-img active">
        <?php
         if ($this->modules[9]) {
           for ($i=0; $i < count($this->modules[9]['album']); $i++) {
            echo "<li><img src=\"".$this->modules[9]['album'][$i]['path']."\" alt=\"\"/></li>";
           }
         }
        ?>
    </ul>
    <ul class="fucked-img">
        <?php
         if ($this->modules[10]) {
           for ($i=0; $i < count($this->modules[10]['album']); $i++) {
            echo "<li><img src=\"".$this->modules[10]['album'][$i]['path']."\" alt=\"\"/></li>";
           }
         }
        ?>
    </ul>
</div>