<!DOCTYPE html>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>明理苑后台管理系统</title>
<link rel="stylesheet" href="/css/admin/reset.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/admin/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/admin/invalid.css" type="text/css" media="screen" />
</head>
  
	<body id="login">
		
		<div id="login-wrapper" class="png_bg">
			<div id="login-top">
			
				<!-- <h1 style="top:100px;text-align: center;width:100%;">明理苑后台管理系统</h1> -->
				<!-- Logo (221px width) -->
				<img id="logo" src="/images/admin/logo.png" alt="明理苑后台管理系统" />
			</div> <!-- End #logn-top -->
			
			<div id="login-content">
				
				<form action="/login/login" method="post">
				
					<div class="notification information png_bg">
						<div class="alt">
							请登录
						</div>
					</div>
					
					<p>
						<label>用户名</label>
						<input class="text-input username" type="text" name="username" />
					</p>
					<div class="clear"></div>
					<p>
						<label>密　码</label>
						<input class="text-input pwd" type="password" name="password" />
					</p>
					<div class="clear"></div>
					<!-- <p id="remember-password">
						<label style="font-size: 13px;"><input type="checkbox" name="remember" />记住我</label>
					</p> -->
					<div class="clear"></div>
					<p>
						<input class="button" type="submit" value="登陆" />
					</p>
					
				</form>
			</div> <!-- End #login-content -->
			
		</div> <!-- End #login-wrapper -->
	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/simpla.jquery.configuration.js"></script>
	<script type="text/javascript" src="/js/admin/login.js"></script>
	<script type="text/javascript">
	  $(document).ready(function(){
	  	$(".username").focus();
	  });
	</script>
  </body>
</html>
