<link rel="stylesheet" type="text/css" media="all" href="/css/admin/jquery-ui.css" />
<link rel="stylesheet" type="text/css" media="all" href="/css/admin/jquery-ui-timepicker-addon.css" />
<div class="content-box">
    <div class="content-box-header">

        <h3 style="cursor: s-resize;">编辑文章</h3>

    </div> <!-- End .content-box-header -->

    <div class="content-box-content" style="display: block;">

        <div class="tab-content default-tab" style="display: block;">

            <div id="add">
                <form class="addForm" method="post">
                        <p>标　题：&nbsp;<input type="text" name="title" class="text-input title" size="90" maxlength="40" placeholder="*必填项" value="<?=$this->oldArticle[0]['title']?>"><!-- <span id="info">0</span>/40字<span id="res" style="color:red"></span> --></p>
                        <p>来　源：&nbsp;<input type="text" name="source" class="text-input source" size="20" maxlength="20"/ placeholder="默认：工大学子"  value="<?=$this->oldArticle[0]['source']?>"> 　&nbsp;; 作　者：&nbsp;<input type="text" name="author" class="text-input author" size="20" maxlength="20" placeholder="默认：无"  value="<?=$this->oldArticle[0]['author']?>"></p>
                        <p>栏　目：
                            <select name="module" class="module">
                                <?php
                                    $arrModule = $this->arrModule;
                                    $rowsmodule = count($arrModule);
                                    for($i=0;$i<$rowsmodule;$i++) {
                                      $selected = ($this->oldArticle[0]['module_id']==$arrModule[$i]['module_id'])?" selected":null;
                                      echo "<option value='".$arrModule[$i]['module_id']."' class='getModule' ".$selected.">".$arrModule[$i]['module_name']."</option>";
                                    }
                                ?>
                            </select>
                        </p>
                        <?php if ($this->session->type == 1) echo
                        "<p>时　间：&nbsp;<input type=\"text\" name=\"publishtime\" id=\"timepicker\" class=\"text-input publishtime\" size=\"22\" style=\"position:relative;z-index:1000;\" value=\"".$this->oldArticle[0]['addtime']."\" placeholder=\"默认：当前时间\" readonly/></p>"; ?>
                        <?php if ($this->session->type == 1) echo
                        "<p>浏览量：&nbsp;<input type=\"number\" name=\"visited\" class=\"text-input visited\" size=\"22\" value=\"".$this->oldArticle[0]['visited']."\" placeholder='0'/></p>"; ?>
                        <script  id="editor" type="text/plain" name="article"  ><?=$this->oldArticle[0]['content']?></script><br /><br />
                        <div id="anniu">
                            <input type="submit" class="btn" value="提交" />
                            <input type="reset" class="btn" value="重置" />
                        </div>
                </form>
            </div>

        </div>

</div> <!-- End .content-box-content -->

</div>
            

<script type="text/javascript" src="/js/admin/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/admin/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" src="/js/admin/jquery-ui-sliderAccess.js"></script>
<script type="text/javascript" src="/js/admin/getColumn.js"></script>
<script type="text/javascript" src="/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/js/admin/jquery.artDialog.js?skin=green"></script>
<script type="text/javascript" src="/js/admin/modifypwd.js"></script>
<script type="text/javascript">

   //实例化编辑器
    UE.getEditor('editor');

    function createEditor(){
        enableBtn();
        UE.getEditor('editor')
    }
    function getAllHtml() {
        alert( UE.getEditor('editor').getAllHtml() )
    }
    function getContent() {
        var arr = [];
        arr.push( "使用editor.getContent()方法可以获得编辑器的内容" );
        arr.push( "内容为：" );
        arr.push(  UE.getEditor('editor').getContent() );
        alert( arr.join( "\n" ) );
    }
    function getPlainTxt() {
        var arr = [];
        arr.push( "使用editor.getPlainTxt()方法可以获得编辑器的带格式的纯文本内容" );
        arr.push( "内容为：" );
        arr.push(  UE.getEditor('editor').getPlainTxt() );
        alert( arr.join( '\n' ) )
    }
    function setContent() {
        var arr = [];
        arr.push( "使用editor.setContent('欢迎使用ueditor')方法可以设置编辑器的内容" );
        UE.getEditor('editor').setContent( '欢迎使用ueditor' );
        alert( arr.join( "\n" ) );
    }
    function setDisabled() {
        UE.getEditor('editor').setDisabled( 'fullscreen' );
        disableBtn( "enable" );
    }

    function setEnabled() {
        UE.getEditor('editor').setEnabled();
        enableBtn();
    }

    function getText() {
        //当你点击按钮时编辑区域已经失去了焦点，如果直接用getText将不会得到内容，所以要在选回来，然后取得内容
        var range =  UE.getEditor('editor').selection.getRange();
        range.select();
        var txt =  UE.getEditor('editor').selection.getText();
        alert( txt )
    }

    function getContentTxt() {
        var arr = [];
        arr.push( "使用editor.getContentTxt()方法可以获得编辑器的纯文本内容" );
        arr.push( "编辑器的纯文本内容为：" );
        arr.push(  UE.getEditor('editor').getContentTxt() );
        alert( arr.join( "\n" ) );
    }
    function hasContent() {
        var arr = [];
        arr.push( "使用editor.hasContents()方法判断编辑器里是否有内容" );
        arr.push( "判断结果为：" );
        arr.push(  UE.getEditor('editor').hasContents() );
        alert( arr.join( "\n" ) );
    }
    function setFocus() {
        UE.getEditor('editor').focus();
    }
    function deleteEditor() {
        disableBtn();
        UE.getEditor('editor').destroy();
    }
    function disableBtn( str ) {
        var div = document.getElementById( 'btns' );
        var btns = domUtils.getElementsByTagName( div, "input" );
        for ( var i = 0, btn; btn = btns[i++]; ) {
            if ( btn.id == str ) {
                domUtils.removeAttributes( btn, ["disabled"] );
            } else {
                btn.setAttribute( "disabled", "true" );
            }
        }
    }
    function enableBtn() {
        var div = document.getElementById( 'btns' );
        var btns = domUtils.getElementsByTagName( div, "input" );
        for ( var i = 0, btn; btn = btns[i++]; ) {
            domUtils.removeAttributes( btn, ["disabled"] );
        }
    }
    $(".btn").eq(0).click(function(){
        if(<?php if ($this->session->type == 1) echo "($(\".dept\").val() ==-1) || ";?>($(".column").val() ==0) || ($(".text-input").eq(0).val() == "") || ($(".text-input").eq(1).val() == "") || ($("iframe").eq(0).contents().find("body").text() == "")){
            if ($(".column").val() ==0) {alert("亲，请选择栏目"); return false;}
            if ($(".text-input").eq(0).val() == "") {alert("亲，请填写标题"); return false;}
            if ($("iframe").eq(0).contents().find("body").text() == "") {alert("亲，请填写文章内容"); return false;}
        }
        else if(($(".text-input").eq(0).val().length) > 40 ){
            alert("亲，文章标题不能多于40字符");
            return false;
        }
        else if(($(".text-input").eq(1).val().length) > 20 ){
            alert("亲，文章来源不能多于20字符");
            return false;
        }
        else 
        {
            return true;
        }   
    });
    
    $(".articletitle").keyup(function(){
        var checkit = $(".articletitle").val();
        $.ajax({
            type:"POST",
            url:'/admin/checkarticletitle',
            data:"checkit="+checkit,
            success:function(data){
                if (data==0) {
                    $("#res").html("&nbsp;&nbsp;*已经存在相同标题！");
                };
            }
        });
    });

    jQuery(function($){
        $.datepicker.regional['zh-cn'] = {
            closeText: '关闭',
            prevText: '&#x3C;上月',
            nextText: '下月&#x3E;',
            currentText: '今天',
            monthNames: ['一月','二月','三月','四月','五月','六月',
            '七月','八月','九月','十月','十一月','十二月'],
            monthNamesShort: ['一月','二月','三月','四月','五月','六月',
            '七月','八月','九月','十月','十一月','十二月'],
            dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],
            dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],
            dayNamesMin: ['日','一','二','三','四','五','六'],
            weekHeader: '周',
            dateFormat: 'yy-mm-dd',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: true,
            yearSuffix: '年'};
        $.datepicker.setDefaults($.datepicker.regional['zh-cn']);
    });

    $("#timepicker").datetimepicker({
        timeOnlyTitle: '选择时间',
        timeText: '　时间',
        hourText: '　时',
        minuteText: '　分',
        secondText: '　秒',
        currentText: '现在',
        closeText: '完成',
        dateFormat: "yy-mm-dd",
        timeFormat: 'HH:mm:ss',
        stepHour: 1,
        stepMinute: 1,
        stepSecond: 1,
    });


    $(".addForm").submit(function(){
      var title = $.trim($(".title").val());
      var source = $.trim($(".source").val());
      var author = $.trim($(".author").val());
      var module_id = $.trim($(".module").val());
      <?php 
      if ($this->session->type == 1) {
        echo 'var publishtime = $.trim($(".publishtime").val());var visited = $.trim($(".visited").val());';
      }
      else {
        echo 'var publishtime = "";var visited = "";';
      }
      ?>
      var article = $("iframe").eq(0).contents().find("body").html();
      if (title == ''||module_id == ''||article == '') {
        return false;
      }
      if (source == '') {
        source = '工大学子';
      }
      if (author == '') {
        author = '无';
      }
      addArt(title,source,author,module_id,publishtime,visited,article);
      return false;
    });

function addArt(title,source,author,module_id,publishtime,visited,article){
  $.ajax({
    url:"/admin/writearticle/type/edit",
    type:"post",
    data:{
      aid:<?=$this->oldArticle[0]['id']?>,
      title:title,
      source:source,
      author:author,
      module_id:module_id,
      publishtime:publishtime,
      visited:visited,
      article:article
    },
    success:function(msg){
      if (msg == 'success') {
        alert("修改成功");
        // location.href="/admin";
      }
      else {
        alert("修改失败，请检查相关选项是否符合要求");
      }
    }
  });
  return false;
}
</script>